name: Continuous Integration
on: [push]
jobs:

  test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    name: fmt, lint, test
    env:
      ENVIRONMENT: ci
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run fmt
        run: make fmt

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test

